name: Audit Pricing

on:
  schedule:
    - cron: '30 3 * * *' # Nightly at 03:30 UTC
  workflow_dispatch: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run pricing audit
        run: npm run audit:pricing

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pricing-audit
          path: |
            data/pricing-audit.json
            data/pricing-audit.md

      - name: Enforce zero anomalies
        run: |
          node -e "const fs=require('fs'); const j=JSON.parse(fs.readFileSync('data/pricing-audit.json','utf8')); if (j.anomalies && j.anomalies.length){ console.error('Pricing anomalies found:', j.anomalies.length); process.exit(1); } else { console.log('No pricing anomalies.'); }"

      - name: Commit audit summary (optional)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/pricing-audit.*
            git commit -m "chore(pricing): update audit report (CI)" || true
            git push || true
          fi
