name: Export Firestore tools to public/tools.json

on:
  workflow_dispatch: {}
  schedule:
    # Daily at 04:15 UTC
    - cron: '15 4 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  export:
    runs-on: ubuntu-latest
    outputs:
      additions: ${{ steps.meta.outputs.additions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Write Firebase service account key
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -z "$FIREBASE_SERVICE_ACCOUNT_JSON" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT_JSON secret is not set" >&2
            exit 1
          fi
          KEY_FILE="$RUNNER_TEMP/serviceAccount.json"
          printf "%s" "$FIREBASE_SERVICE_ACCOUNT_JSON" > "$KEY_FILE"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$KEY_FILE" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Enrich tools in Firestore (move-left)
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          # Enrich active tools directly in Firestore so exporter just copies through
          KEY_FILE="$RUNNER_TEMP/serviceAccount.json"
          printf "%s" "$FIREBASE_SERVICE_ACCOUNT_JSON" > "$KEY_FILE"
          export GOOGLE_APPLICATION_CREDENTIALS="$KEY_FILE"
          npm run tools:enrich:firestore

      - name: Run exporter
        # Exporter no longer enriches by default; it copies enriched fields from Firestore
        run: npm run export:tools

      - name: Validate tools.json
        env:
          STRICT: '1'
        run: |
          # Validate and summarize; STRICT controls failure after grace period
          npm run tools:validate

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: export tools from Firestore (CI)"
          title: "chore: export tools from Firestore (CI)"
          body: |
            This PR appends newly approved tools from Firestore to public/tools.json.

            Safety notes:
            - Exporter is append-only, preserves existing tools and domain order
            - Skips write when no additions
            - Enforces github.com link policy (allowlist: GitHub Copilot)
          branch: ci/export-tools
          delete-branch: true
          add-paths: |
            public/tools.json

      - name: Add job summary
        run: |
          echo "### Export Tools Summary" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.cpr.outputs.pull-request-number }}" = "" ]; then
            echo "No changes detected; no PR created." >> $GITHUB_STEP_SUMMARY
          else
            echo "PR #${{ steps.cpr.outputs.pull-request-number }} created: ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "Validation STRICT mode: ENFORCED (applies to NEW tools only)" >> $GITHUB_STEP_SUMMARY

      - name: Flag additions
        id: meta
        run: |
          if [ "${{ steps.cpr.outputs.pull-request-number }}" = "" ]; then
            echo "additions=0" >> $GITHUB_OUTPUT
          else
            echo "additions=1" >> $GITHUB_OUTPUT
          fi

    # Notes:

  trigger-popularity:
    if: needs.export.outputs.additions == '1'
    needs: export
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Dispatch popularity workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-popularity.yml
          ref: main
    # - Set repository secret FIREBASE_SERVICE_ACCOUNT_JSON to the raw JSON of your Firebase service account key.
    # - The exporter enforces the GitHub link exclusion policy (allowlisting GitHub Copilot).
    # - Update the cron schedule as needed.
