name: ML Retrain (weekly)

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ML dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ml/requirements.txt

      - name: Train moderation model
        run: |
          if [ ! -f data/submissions_labeled.json ]; then
            echo 'No labeled data found at data/submissions_labeled.json; skipping training.'
            exit 0
          fi
          python ml/train_moderation_model.py

      - name: Upload model artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ml-model
          path: ml/model_v1.joblib
          if-no-files-found: ignore
