name: Pricing Approval

on:
  workflow_dispatch:
    inputs:
      section:
        description: 'Section slug (domain)'
        required: true
      tool:
        description: 'Tool name'
        required: true
      pricing:
        description: 'Approved pricing model (Open Source, Free, Freemium, Subscription)'
        required: true

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Apply override
        id: apply
        run: |
          node -e "
          const fs=require('fs');
          const path=require('path');
          const sec=process.env.SECTION; const tool=process.env.TOOL; const pricing=process.env.PRICING;
          const key=(sec+'::'+tool).toLowerCase();
          const p=path.join(process.cwd(),'data','pricing-overrides.json');
          let j={}; try{ j=JSON.parse(fs.readFileSync(p,'utf8')); }catch{}
          j[key]=pricing; fs.mkdirSync(path.dirname(p),{recursive:true}); fs.writeFileSync(p, JSON.stringify(j,null,2));
          console.log('Applied override for', key, '->', pricing);
          "
        env:
          SECTION: ${{ github.event.inputs.section }}
          TOOL: ${{ github.event.inputs.tool }}
          PRICING: ${{ github.event.inputs.pricing }}
      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Pricing approval: ${{ github.event.inputs.tool }} -> ${{ github.event.inputs.pricing }}"
          content-filepath: .github/ISSUE_TEMPLATE/pricing-approval.md
          labels: pricing,automation
        continue-on-error: true
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(pricing): override ${{ github.event.inputs.tool }} -> ${{ github.event.inputs.pricing }}"
          title: "chore(pricing): override ${{ github.event.inputs.tool }} -> ${{ github.event.inputs.pricing }}"
          body: |
            Approved via workflow_dispatch.
            Section: ${{ github.event.inputs.section }}
            Tool: ${{ github.event.inputs.tool }}
            Pricing: ${{ github.event.inputs.pricing }}
          branch: ci/pricing-approve-${{ github.event.inputs.section }}-${{ github.event.inputs.tool }}
          delete-branch: true