name: Pricing Approval (Issue)

on:
  issues:
    types: [opened]

jobs:
  from-issue:
    if: contains(join(github.event.issue.labels.*.name, ','), 'pricing-approve')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Parse issue and apply override
        id: parse
        run: |
          node -e "
          const fs=require('fs');
          const path=require('path');
          const ev=JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH,'utf8'));
          const body=String(ev.issue.body||'');
          function pick(key){ const re=new RegExp('^'+key+':\\s*(.+)$','mi'); const m=body.match(re); return m?m[1].trim():''; }
          const section=pick('Section');
          const tool=pick('Tool');
          const pricing=pick('Pricing');
          if(!section||!tool||!pricing){ console.error('Missing Section/Tool/Pricing in issue body'); process.exit(1); }
          const key=(section+'::'+tool).toLowerCase();
          const p=path.join(process.cwd(),'data','pricing-overrides.json');
          let j={}; try{ j=JSON.parse(fs.readFileSync(p,'utf8')); }catch{}
          j[key]=pricing; fs.mkdirSync(path.dirname(p),{recursive:true}); fs.writeFileSync(p, JSON.stringify(j,null,2));
          console.log('Applied override for', key, '->', pricing);
          fs.writeFileSync('._pr_body.txt', `Approved via issue.\nSection: ${section}\nTool: ${tool}\nPricing: ${pricing}\n`);
          "
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(pricing): override from issue"
          title: "chore(pricing): override ${{ github.event.issue.title }}"
          body-path: ._pr_body.txt
          branch: ci/pricing-approve-${{ github.event.issue.number }}
          delete-branch: true
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Override applied and PR opened. Thank you!