name: Update Context Log

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (YYYY-MM-DD); defaults to today (UTC)'
        required: false
      apply:
        description: 'Write changes & commit (true) or dry-run (false)'
        required: false
        default: 'false'
      extra_entry:
        description: 'Optional additional bullet (can run multiple times)'
        required: false
      auto_commits:
        description: 'Harvest commit messages for the date (true/false)'
        required: false
        default: 'true'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (if package.json present)
        run: |
          if [ -f package.json ]; then npm ci --ignore-scripts; fi

      - name: Build entry args
        id: build
        run: |
          DATE_INPUT="${{ github.event.inputs.date }}"
          if [ -z "$DATE_INPUT" ]; then DATE_INPUT=$(date -u +%Y-%m-%d); fi
          ARGS="--date $DATE_INPUT"
          if [ "${{ github.event.inputs.auto_commits }}" = "true" ]; then ARGS="$ARGS --auto-commits"; fi
          if [ -n "${{ github.event.inputs.extra_entry }}" ]; then ARGS="$ARGS --entry '${{ github.event.inputs.extra_entry }}'"; fi
          echo "args=$ARGS" >> $GITHUB_OUTPUT

      - name: Dry Run Update
        if: ${{ github.event.inputs.apply != 'true' }}
        run: |
          node scripts/update-context-log.mjs ${{ steps.build.outputs.args }} --allow-empty || true
          echo 'Dry run complete (no commit).'

      - name: Apply and Commit
        if: ${{ github.event.inputs.apply == 'true' }}
        run: |
          node scripts/update-context-log.mjs ${{ steps.build.outputs.args }} --allow-empty || true
          if git diff --quiet; then
            echo 'No changes to commit.'
          else
            git config user.name 'github-actions'
            git config user.email 'actions@github.com'
            git add docs/context-log.md
            git commit -m "docs(context-log): auto-update for ${{ github.event.inputs.date || 'today' }}" || echo 'Nothing to commit'
            git push
          fi
