name: Update Popularity

on:
  schedule:
    - cron: '0 3 * * 1,4' # Twice weekly at 03:00 UTC (Mon, Thu)
  workflow_dispatch: {}

jobs:
  update:
    permissions:
      contents: write
    concurrency:
      group: popularity-update
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-audit --no-fund --omit=dev

      - name: Run popularity update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node ./scripts/update-popularity.mjs

      - name: Commit and push popularity outputs
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git fetch origin "${{ github.ref_name }}"
            git add data/popularity_raw.json public/popularity.json public/popularity_ranks.json
            git commit -m "chore(popularity): refresh signals and ranks"
            git pull --rebase origin "${{ github.ref_name }}" || true
            git push origin HEAD:"${{ github.ref_name }}"
          else
            echo "No changes to commit."
          fi
