name: Update Popularity

on:
  schedule:
    - cron: '17 3 * * *'  # Daily at 03:17 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run updater
        run: |
          npm ci --ignore-scripts --no-audit --no-fund || echo "No lockfile; continuing"
          node ./scripts/update-popularity.mjs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/popularity.json public/popularity_ranks.json data/popularity_raw.json
          git commit -m "chore(popularity): daily refresh" || echo "No changes to commit"
          git push

      - name: Email Top 30 (after update)
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: node ./scripts/email-top-popularity.mjs
