name: Update Popularity

on:
  schedule:
    - cron: '0 3 * * 1,4' # Twice weekly at 03:00 UTC (Mon, Thu)
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci --omit=dev

      - name: Run popularity update
        run: node ./scripts/update-popularity.mjs

      - name: Commit and push popularity outputs
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/popularity_raw.json public/popularity.json public/popularity_ranks.json
            git commit -m "chore(popularity): refresh signals and ranks"
            git push
          else
            echo "No changes to commit."
          fi
name: Update Popularity

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 01:30 UTC (07:00 IST)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run updater
        run: |
          npm ci --ignore-scripts --no-audit --no-fund || echo "No lockfile; continuing"
          node ./scripts/update-popularity.mjs

      - name: Commit and push changes
        id: commit_push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/popularity.json public/popularity_ranks.json data/popularity_raw.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "pop_changed=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore(popularity): daily refresh"
            git push
            echo "pop_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Email Top 30 (after update)
        if: steps.commit_push.outputs.pop_changed == 'true'
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: node ./scripts/email-top-popularity.mjs
